= Paŝo unua

== 1

Leginte la supran fabelon, respondu jenajn demandojn.

[qanda]
Kion faris Sen Dubo kaj lia amiko antaŭ ol tiu lasta rakontis la fabelon?::
Ili trinkis?

Kial Ripsrops haltigis sian aŭtomobilon proksime al Kopenhago?::
Por aĉeti aferojn por la domo.

Kiun lingvon parolis la rano?::
Ĝi parolis la danan.

"... la petita varmo ne kostos al li elspezojn." Kion tiuj vortoj sciigas al ni pri Ripsrops?
Ke li ne volonte uzas sian monon.

Kion donis Ripsrops al la rano dumvojaĝe?::
Akvon kaj manĝon.

Kial Ripsrops hezitis konsenti, ke la rano dormu ĉe li?::
Ĉar neniu volis ĝis tiam dormi en sia familia lito.

Pro kiuj kialoj li fine konsentis?::
Ĉar sia edzino estis for.

Kio okazis al la rano dum Ripsrops pretigis sin por dormo?::
Ĝi fariĝis reĝidino.

Kiajn vestojn portis la reĝidino?::
Nur noktovestojn.

Kio okazis antaŭ ol Ripsrops povis enlitiĝi?::
Sia edzino alvenis el sia feriado.

== 2

Jen estas kelkaj respondoj. Skribu la faritajn demandojn

Lia nomo estis Sen Dubo.::
Kiel nomiĝis la amiko de la rakontanto?

De Arĥangelsk ĝis Kopenhago.::
De kie al kiel veturis Ripsrops?

Li iom promenis.::
Kion faris Ripsrops antaŭ ol aŭdi la rano?

Ĝi promesis, ke li ricevos bonon.::
Kion promesis la rano al Ripsrops?

Ĉar estis varme.::
Kial Ripsrops miris kiam la rano diris ke ĝi frostas?

Li metis ĝin en sian poŝon.::
Kion faris Ripsrops por varmigi la ranon?

En lia lito.::
Kie la rano volis dormi?

Li tute teruriĝis.::
Kiel reagis Ripsrops kiam la rano fariĝis reĝidino?

Kion diris la reĝidino-fariĝita rano?::
"Rri-ipsĉjo!"

Ne, mi ĝin ne kredas.::
Ĉu vi kredas la rakonto?
