= Paŝo unua

== 1

Leginte la supran fabelon, respondu jenajn demandojn.

[qanda]
Kion faris Sen Dubo kaj lia amiko antaŭ ol tiu lasta rakontis la fabelon?::
Ili trinkis?

Kial Ripsrops haltigis sian aŭtomobilon proksime al Kopenhago?::
Por aĉeti aferojn por la domo.

Kiun lingvon parolis la rano?::
Ĝi parolis la danan.

"... la petita varmo ne kostos al li elspezojn." Kion tiuj vortoj sciigas al ni pri Ripsrops?
Ke li ne volonte uzas sian monon.

Kion donis Ripsrops al la rano dumvojaĝe?::
Akvon kaj manĝon.

Kial Ripsrops hezitis konsenti, ke la rano dormu ĉe li?::
Ĉar neniu volis ĝis tiam dormi en sia familia lito.

Pro kiuj kialoj li fine konsentis?::
Ĉar sia edzino estis for.

Kio okazis al la rano dum Ripsrops pretigis sin por dormo?::
Ĝi fariĝis reĝidino.

Kiajn vestojn portis la reĝidino?::
Nur noktovestojn.

Kio okazis antaŭ ol Ripsrops povis enlitiĝi?::
Sia edzino alvenis el sia feriado.

== 2

Jen estas kelkaj respondoj. Skribu la faritajn demandojn.

Lia nomo estis Sen Dubo.::
Kiel nomiĝis la amiko de la rakontanto?

De Arĥangelsk ĝis Kopenhago.::
De kie al kiel veturis Ripsrops?

Li iom promenis.::
Kion faris Ripsrops antaŭ ol aŭdi la rano?

Ĝi promesis, ke li ricevos bonon.::
Kion promesis la rano al Ripsrops?

Ĉar estis varme.::
Kial Ripsrops miris kiam la rano diris ke ĝi frostas?

Li metis ĝin en sian poŝon.::
Kion faris Ripsrops por varmigi la ranon?

En lia lito.::
Kie la rano volis dormi?

Li tute teruriĝis.::
Kiel reagis Ripsrops kiam la rano fariĝis reĝidino?

Kion diris la reĝidino-fariĝita rano?::
"Rri-ipsĉjo!"

Ne, mi ĝin ne kredas.::
Ĉu vi kredas la rakonto?

== 3

Kion, laŭ via opinio, diris s-ino Ripsrops al sia edzo, kiam li rakontis sian historion?

S-ino Ripsrops tute ne kredis sian rakonton. Eble, ŝi demandis al lin foriri el la loĝejo. Eble, ŝi mem foriris la loĝejo kaj trovis iun ajn hotelon por tranokti kaj por ne tranokti sur la lito kie la rano kuŝis.

== 4.

En la sekvantaj frazoj, elektu la ĝustan vorton inter krampoj:
1. Ĉar mi (**SUPOZIS**/SUPOZIGIS) lin fidinda, al li mi ne (SUPOZIS/**SUPOZIGIS**) la malveron.
2. Ĉar mi volis mem (**RIPOZI**/RIPOZIGI), mi klopodis (RIPOZI/**RIPOZIGI**) la infanon.
3. Viaj deziroj (EFEKTIVIGOS/**EFEKTIVIĜOS**) se vi scios mem (**EFEKTIVIGI**/EFEKTIVIĜI) ilin.
4. La fortegulo (TERURIĜIS/**TERURIS**) la vilaĝanojn; ili tiel (**TERURIĜIS**/TERURIS), ke ill forkuris.
5. Unue li (ENLITIĜIS/**ENLITIGIS**) siajn gefilojn, poste li (**ENLITIĜIS**/ENLITIGIS) mem.
6. Tiu libro (DATAS/**DATIĜAS**) de la deka jarcento; fama historiisto (DATIS/**DATIGIS**) ĝin.
7. Eksterleĝuloj kaptis la vilaĝon; per do multaj havindaĵoj (**KAPTIGIS**/KAPTIĜIS).
8. Kiam mi (ELPUTIĜIS/**ELPUTIGIS**) akvon, samtempe (ELPUTIGIS/**ELPUTIĜIS**) tri ranoj.

== 5

Jen estas kvin adjektivoj; substantivigu ilin, kaj uzu en frazoj:

MODERNA MODESTA ORDINARA SOBRA CERTA.

- En la moderno la junularo ne plu respektas la plenkreskuloj.
- Modesto estas mia unua valoro kiam mi decidas kion surhavi.
- Libroj parolas pri tri temoj: la vojaĝo de la heroo, la nereciprokita amo, kaj la ordinaro.
- Siaj vortoj estas malsamaj en la sobro kaj post la bieroj.
- Ne estas facile paroli kun tiom de certoj kiam oni menongas.

== 6

La antaŭajn berlinajn vinterojn vere estis froste sed nun estas apenaŭ 1 grado.

Estos danĝero tiel paroli al la ĉefo.

Estas junio sed estas malvarme.

Vidi la bovoj morti, estis nekontentige.

Kiam ni trovis novan laboron, estis ĝojige.

Iĝis certe ke oni ne plu havos concertojn ĉi-jaron.

Iĝas neeble iri al la laboro kiam neĝas.

Iĝos urĝe iri al la necesejo.

Iĝis mallume kaj ni dormemis.

Iĝas nedezirinde ke la kompanio ne havas sufiĉe da kunlaborantoj.
